import { IsEnum, IsString, MinLength } from "class-validator";
import { TenantType } from "@prisma/client";

/**
 * Self-serve org signup: creates the organization + its first admin.
 * The admin's login email is generated by the system from the org name
 * (e.g. "Acme Hospital" -> acme.hospital@noloop.in).
 */
export class SignupDto {
  @IsString()
  @MinLength(2)
  orgName!: string;

  @IsEnum(TenantType)
  orgType!: TenantType; // HOSPITAL | INSURER

  @IsString()
  @MinLength(2)
  adminName!: string;

  @IsString()
  @MinLength(8)
  password!: string;
}
